### ISSUE TITLE
Astral Projection Teleport Bug

### ISSUE THREAD

**Issue by TheCookiesKing** [Technicman69/Tentacle-System#1]
Astral Projection allows players to teleport to other players/anywhere by suffocating the Skeleton that replaces you

https://github.com/user-attachments/assets/ed783d8a-cd6e-445a-98b4-9897adb7b93d

**Comment by Technicman69** [comment]
As this part of code is from Omni Gazer 1.2 written by NotPog himself, it's kinda not my problem.

I'll try to take a closer look at this in the future tho

**Comment by Technicman69** [comment]
Fixed, now the body can't be damaged without an attacker
